#
# 	Meteora for Jekyll by Gatsby.io		    
#
#   A Jekyll 3 Theme for programmers, coders & hackers. Licensed under the MIT License
#
#	Website: https://gatsby.io
#	Github: https://github.com/GatsbyHQ/meteora-jekyll
#

# Setup
title:            Met&eacute;ora Jekyll
tagline:          A Jekyll 3 Theme
description:      A simple Jekyll 3 Theme developed by Gatsby.io for programmers, coders &amp; hackers
baseurl:          /

# Dependencies
markdown: 		  kramdown
highlighter: 	  pygments
encoding: 		  UTF-8
permalink:        ":title/"

# Permalinks
permalink: 		  pretty

# Custom Variable
twitter:
  username:		  GatsbyHQ
  
github:
  username:       GatsbyHQ
  
# Addon Gems for Jekyll
gems: 			  [jekyll-paginate]
paginate: 		  3